name: GTests

on: [push]


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      name: 'Hello World'
      description: 'Greet someone and record the time'
      inputs:
        exec-path:  # id of input
          description: 'Path to executable for running tests'
          required: true
        report-path:
          description: 'Output path to report'
          required: true
        working-directory:
          description: 'Path to workdir'
          required: True
      outputs:
        time: # id of output
          description: 'The time we greeted you'
      runs:
        using: 'node12'
        main: 'index.js'

