name: GTests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .

    - name: Test
      description: 'Greet someone and record the time'
      inputs:
        exec-path:  # id of input
          description: 'Path to executable for running tests'
          required: true
        report-path:
          description: 'Output path to report'
          required: true
        working-directory:
          description: 'Path to workdir'
          required: True
      outputs:
        time: # id of output
          description: 'The time we greeted you'
      run: make
