name: CMake
on: [push]
env: 
  BUILD_TYPE: Release
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v3
      -
        name: CREATE DIRECTORIES
        run: "cd task6 && mkdir 3rdparty && mkdir build && mkdir res && dir=$(pwd)"
      - 
        name: Build
        run: "cd task6 && git clone https://github.com/google/googletest.git && mv googletest 3rdparty && cd build && cmake -DCMAKE_INSTALL_PREFIX=${dir}/res .. && make && make install"
      - 
        uses: akhtyamovpavel/ActionGtestReport@v0.0.9
        with: 
          exec-path: bin/CTestExe
          report-path: report.xml
          working-directory: task6/
      - 
        name: Test
        run: "tar -czf test-report.tar.gz report.xml"
        working-directory: task6/
      - 
        name: UploadArtifacts
        uses: actions/upload-artifact@v1
        with: 
          name: Distributive
          path: task6/res/exe/
