name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: some dir
      working-directory: ${{github.workspace}}/task6
      run: mkdir build && mkdir 3rdparty
    
    - name: Install gtest manually
      working-directory: ${{github.workspace}}/task6/3rdparty
      run: sudo apt install git && git clone https://github.com/google/googletest.git -b release-1.11.0

    - name: Build
      working-directory: ${{github.workspace}}/task6/build
      # Build your program with the given configuration
      run: cmake ..
      
    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUDBYTES_PROD }}"
        channelId: live
        projectId: cloudbytes-prod
        report-path: test-report/report.xml
          
          
          
