name: CMake

on:
  push:
    branches: [task6]
  
  pull_request:
    branches: [task6]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: some dir
      run: cd task6 && mkdir build && mkdir 3rdparty && mkdir result && dir=$(pwd) 
    
    - name: Install gtest manually
      run: cd task6 && cd 3rdparty && git clone https://github.com/google/googletest.git

    - name: Build
      # Build your program with the given configuration
      run: cd task6 && cd build && cmake -DCMAKE_INSTALL_PREFIX=${dir}/result ..
      
    - uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        working-directory: task6
        exec-path: bin/CTestExe
        report-path: report.xml
        
         
    - name: Test
      run: cd task6 && tar -cvzf test-report.tar.gz report.xml
      
    - name: UploadArtifacts
      uses: actions/upload-artifact@v1
      with:
        name: Distributive
        path: task6/result/exe/
            
